### ISSUE TITLE
Incompatibility between v2 and v4 on "history accessible from the activation of this option"

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#109]
### Steps to reproduce

Activate "history accessible from the activation of this option" on v4
![image](https://user-images.githubusercontent.com/1238254/179392665-4e7a80cd-e030-481a-9b23-4544a95f88ef.png)
On v2, the room will be difficult to access.

### Solution
Disable this option if Tchap V2 is still in production

**Comment by estellecomment** [comment]
@jdauphant What problem does this create in practice ?

**Comment by jdauphant** [comment]
I don't remember well but I had to revert a setting, the room wasn't accessible anymore on my tchap web v2.
We should test with multiples accounts

**Comment by mcalinghee** [comment]
### Tests
**Scenario 1**
1. Create a new private room with user1
2. Write a message A
3. Change the settings to : `Members only (since the point in time of selecting this option)`
4. Write a message B
5. Invite user2 to the private room
6. user2 can see the message B not the message A in v2 and v4
In v2:
<img width="1200" alt="Screenshot 2022-10-04 at 16 42 51" src="https://user-images.githubusercontent.com/3725676/193850984-53854845-cc3c-4d12-8efa-15e41d4163cc.png">
In v4:
<img width="905" alt="Screenshot 2022-10-04 at 16 37 58" src="https://user-images.githubusercontent.com/3725676/193850845-6349bdd8-e67b-4428-a63e-f3d59693643c.png">
=> Test : OK - No Issue detected here

**Comment by mcalinghee** [comment]
V4 is in prod now
