### ISSUE TITLE
[devops+dev] Avoid regressions with E2E Tests

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#117]
- [ ] add a test framework (with cypress used by element)
- [ ] add one UI test on Login Page (failure scenario to start with)
- [ ] add CI to automate test (maybe with app on scalingo)

Goals : 
 - get something simple that works (we can do more complicated later)
 - avoid regressions !

**Comment by estellecomment** [comment]
Note : the github actions (if we use that) will need the test user's username and password. We can store that in organisation secrets : https://github.com/organizations/tchapgouv/settings/secrets/actions

**Comment by celiacheff** [comment]
My retex on trying the existing tests:

Tchap must be launched in English, because some identifiers are hardcoded in English, or we can translate the strings
- ex: `[aria-label="User Menu"] <-> [aria-label="Menu utilisateur"]`

The registration must be updated to our custom component
- fail on: **get** .mx_ServerPicker_change which is not found
- registerUser should be replaced in synapse.ts

We could use the dev server instead of the docker
- using the var ’env `PUBLIC_BASEURL`

**Comment by celiacheff** [comment]
Lien vers le Notion de travail, l'info est trop brouillonne pour que je le mette ici pour le moment https://www.notion.so/mercurial-timer-ec4/Cypress-E2E-Test-4758a466709047d19c9874e93cb32c87

**Comment by celiacheff** [comment]
Mes remarques actuelles

- Actuellement je teste avec le docker, il faudra mettre à jour avec le docker synape. Il faudra utiliser le futur docker synapse Tchap.
- pour la CI/CD: il faut copier le config.json de dev et lancer le serveur.
