### ISSUE TITLE
Login : users must know their homeserver

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#151]
Users must choose their home server to login. 

Problem : in V2 users have no idea of what is a homeserver

![Capture d’écran 2022-09-02 à 15 41 45](https://user-images.githubusercontent.com/4077729/188159007-334f2afe-0c93-472d-b484-06c30cfd7d08.png)

Alternative :   
- mail all users to tell which homeserver they belong to

**Comment by estellecomment** [comment]
Possible implementation (WIP, I will edit this comment as I go)
- replace the serverPicker with a TchapServerPicker : display an email text field, and a Validate button. When button is clicked, we make an API call to find homeserver and set it back in the callback (same callback as the original serverPicker)
- In Login, remove the flows we don’t need.
- Replace PasswordLogin with a TchapPasswordLogin : display just the password field, and pass it the user email (no additional user email field). Keep the same Login button, which passes the same data.

Also possible : replace the whole Login.tsx, because it seems excessively complicated for us.
But it contains a whole lot of little helpers all over which we want to use. Maybe reuse the pieces to make a simpler Login ? (is Login actually NOT simple, so trying to take shortcuts would be a bad idea ?)

**Comment by odelcroi** [comment]
Another approach would be to backport this customization : https://github.com/tchapgouv/tchap-web/blob/ae04a62bc4c59d027fb7e397e6357610e4127c9c/matrix-react-sdk/src/components/structures/auth/Login.js#L144

It seems a quick win isn't it?

**Comment by estellecomment** [comment]
fixed by #196
