### ISSUE TITLE
As a user I want to reset my password

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#156]
### Your use case
I have lost my password, I need to reset it

### Have you considered any alternatives?

NB : update password from a login session works 

_No response_

**Comment by estellecomment** [comment]
- From the login page, click "Forgot my password" and follow the procedure. It works.

The messaging insists that you will be logged out of your existing sessions, which is not necessarily the case now, because there is a checkbox for it (by default you are not logged out of all your sessions).

I also tested the checkbox : if you select "log out all sessions" it does, and if you don't select, it doesn't.

Filed issue to adapt messaging : https://github.com/tchapgouv/tchap-web-v4/issues/206

- From the user settings, you can also change the password. It works. Other sessions are not logged out. This is consistent with v2.


Closing this, no problem.
