### ISSUE TITLE
Loging out : no warning on keys backup

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-web-v4#185]
in v2 when logging out, users are warned about the fact they will lose everything, their keys
<img width="729" alt="Capture d’écran 2022-09-19 à 16 24 44" src="https://user-images.githubusercontent.com/4077729/191040909-4ff31ae4-2faa-4dcd-98f1-be68c6f10dbe.png">

in V4, they are warned also but the consequences are not obvious
<img width="601" alt="Capture d’écran 2022-09-19 à 16 28 14" src="https://user-images.githubusercontent.com/4077729/191041664-a87d72b7-6204-40cd-bf6f-058110c7f81b.png">

- [ ] PR https://github.com/tchapgouv/tchap-web-v4/pull/291

**Comment by odelcroi** [comment]
Sometimes they are not warned. It seems that, they are not warned because they haven't write any message, then losing their keys won't have any effect. need double check

**Comment by estellecomment** [comment]
In V2 we did some UX work around the loss of keys, which includes dialogs at log out. The text is tchap-custom, and maybe come dialogs appears only on tchap.
We will need to port this work back into v4.

**Comment by estellecomment** [comment]
> Sometimes they are not warned. It seems that, they are not warned because they haven't write any message, then losing their keys won't have any effect. need double check

yes I have seen this too, empirically and in the code.

**Comment by estellecomment** [comment]
After the first dialog screenshoted above, we also need to edit the second, to use our tchap-specific text : (see the Miro for reference https://miro.com/app/board/o9J_lxa1Nm0=/)
<img width="765" alt="image" src="https://user-images.githubusercontent.com/911434/200642431-6649f81b-352b-4cba-9ccb-c855de7a958b.png">
(not sure why "passphrase" is used instead of "password", since we are using the account password here, not the secure storage passphrase, right ?)

Not that this dialog, ExportE2EKeysDialog, is already modified by a patch. You cannot have two patches editing the same file, so if we continue using a patch here (rather than a customisation ?) we need to have a single patch for all changes in the file.

**Comment by estellecomment** [comment]
Currently, once you export the keys, the file is downloaded, and then you are sent back to the original dialog, "You'll lose access to your encrypted messages". You have to click "I don't want my encrypted messages" to end the flow and log out.

Following the Miro, instead of going back to the original dialog, we want to add a final confirmation dialog.
This was done in v2 here : https://github.com/tchapgouv/matrix-react-sdk/blob/develop/src/async-components/views/dialogs/ExportE2eKeysSuccessDialog.js
It's a new dialog that is not present in element-web.
