### ISSUE TITLE
Roomlist displays private and public rooms in the same way

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#186]
This is confusing for users. Both forums and private rooms are in the same section of roomlist, and with the same icon.

**Comment by odelcroi** [comment]
+ we do not see at a glance if a room allows external users

**Comment by odelcroi** [comment]
@areox-net @Caroline-lawson  Could we work on some UI components to enhance UX on this topic? Should we take the icon from V2 version?

**Comment by Caroline-lawson** [comment]
Another linked problem is that people I spoke with did not know that forums are not crypted conversations. 

Remind me what the icon was in V2?

If it's the padlock, then it makes sense if it's on all types of group conversations. The problem is that the colours are counter intuitive : 
- red for private rooms: they are encrypted and therefore safe in the context of Tchap - a green closed padlock should make more sense here?
- orange for private rooms open to external users: they are also encrypted - orange closed padlock?
- green for forums: they are open to all Tchap users and not encrypted - red open padlock?

If it isn't the padlock - please ignore.

The "wave" icon didn't make much sense to the people I spoke to.

Open to other suggestions of course.

**Comment by areox-net** [comment]
That's a recurring theme. Tchap v1 highlighted this difference by design, with avatar shapes, icons and - later - color labels for redundancy. We moved to a simpler roomlist as we moved toward Element.
After all these iterations, it is my opinion that the best solution is to separate Forums from other conversations. They are something different both in security level and use.
In this specific case, the web UI is particularly suited for this solution, since it already has sections. 
Is it technically difficult to add a "Forums" section? 

The problem still remains with external users. However, last time we talked about this it was decided that this information is relevant once we are inside a room rather than in the roomlist. So my proposal was to display this information in the room header, both on mobile and web.

**Comment by odelcroi** [comment]
> Is it technically difficult to add a "Forums" section?

I would say it is not straightfoward as we need to implement some logic in the right panel. I will investigate it, but in the mean time, could we propose a quick-win solution to be deployed in the coming days?

> So my proposal was to display this information in the room header, both on mobile and web.
Sure, could you propose a design to do so?

**Comment by areox-net** [comment]
@odelcroi A quick solution for now would be to use the same icon that we use on mobile for Forums 
![Screenshot 2022-10-12 at 11 41 40](https://user-images.githubusercontent.com/1255251/195308947-3cb2bcfd-a334-4c09-940b-8718cd83b961.png)

For the header, my old proposals looked like this 
![Screenshot 2022-10-12 at 11 43 29](https://user-images.githubusercontent.com/1255251/195309371-73b3e4cd-3a0b-413d-86c9-be364af379cc.png)

**Comment by odelcroi** [comment]
Thanks, what can be done easily is to replace the globe by the image you propose. Could you provide a svg version ?
![Capture d’écran 2022-10-12 à 16 39 58](https://user-images.githubusercontent.com/4077729/195373309-94b2fbc6-9c2f-44b1-af8f-22d59d1a363c.png)

**Comment by areox-net** [comment]
Here you go 
![icn_forum](https://user-images.githubusercontent.com/1255251/195376136-480cbbf9-8963-4ea4-ad6a-b67f7df24bdd.svg)

**Comment by estellecomment** [comment]
Question : Can we add a separate category in the roomlist, for public forums ? 
Answer : not easily.

There is no provided hook to do this. We need to edit multiple files all over react-sdk.
The sections of the roomlist correspond to a list of tags defined in [src/stores/room-list/models.ts](https://github.com/matrix-org/matrix-react-sdk/blob/630511de1c6d700197899cb6e3120cd0a734cc72/src/stores/room-list/models.ts#L33). The tag for "Rooms" is "Untagged". We could add our extra tag "PublicRooms" there.
Then we need to edit a number of functions everywhere. [Text-search for `DefaultTagID.DM`](https://cs.github.com/matrix-org/matrix-react-sdk?q=%22DefaultTagID.DM%22) (the tag for DM category) gives a good idea of where to implement things. There is a complicated system with Algorith, events for modifications of the roomlist, etc.

Overall it will be hard to test that our customized roomlist works properly, and resists future upgrades of react-sdk. 
If this is important we should push it into element-web directly.

**Comment by estellecomment** [comment]
Implemented for forums :
<img width="340" alt="image" src="https://user-images.githubusercontent.com/911434/196460344-5ed59d02-5bc8-4dbd-821a-a9caaaacdf84.png">

While we're at it, we could also display the red lock on private rooms, and the orange lock on private-with-externs.

**Comment by Caroline-lawson** [comment]
Why didn't we change the colour of the padlocks? 
- Green for salons privés
- Orange for salons privés ouverts aux externes
- Red for forums

**Comment by estellecomment** [comment]
@Caroline-lawson since then, we have ! https://github.com/tchapgouv/tchap-web-v4/pull/258

**Comment by Caroline-lawson** [comment]
I'm still not seeing it, but if you say it's there, great! 😄
