### ISSUE TITLE
On failed login, no error message displays 

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#201]
With my cross3 account, on localhost, prod backend.
Console says - `Login failed M_FORBIDDEN: Unknown message`
Server request returns 403, no error message.

Happens when account does not exist. 
When email exists and password is wrong, the error message displays alright.

(not done investigating, this is preliminary findings)

**Comment by odelcroi** [comment]
Another error not shown :   
`POST https://matrix.agent1.tchap.incubateur.net/_matrix/client/r0/login 429 (Too Many Requests)`

I guess it is because I tried too many bad password. 

EDIT: I tried again and got this error : 
EDIT EDIT : I tried again and got no displayed error 
![Capture d’écran 2022-09-26 à 09 46 37](https://user-images.githubusercontent.com/4077729/192221611-bdbad805-a7c1-4b22-a882-93265af9f146.png)
