### ISSUE TITLE
[Limitation] Tchap-web_v4 ignores the incoming room key requests until the cross-signing is supported

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#203]
After having deactivating cross signing in Tartine, the client does not start the emoji device verification whenever another device requests key exchange.

### with iphone
- user has an Tartine session (no other sessions)
- user starts iphone 2.0.5 session
- iphone 2.0.5 requests keys from Tartine.
→ KO. emoji exchange does not start. Tartine seems to receive the event but does not treat it.

### with android 
- user has an Tartine session (no other sessions)
- user_1 se connecte a android
- android doit demander les clefs à Tartine
→ KO. emoji exchange does not start. Tartine seems to receive the event but does not treat it.

### with another web browser 
- user_1 est connecté Tartine
- user_1 se connecte à Tartine sur un autre domain (https://app-v4.prod.tchap.incubateur.net/)
- Tartine doit demander les clefs a Tartine
→ KO. emoji exchange does not start. Tartine seems to receive the event but does not treat it.

### logs
In each case we have similar logs in Tartine console : 
https://www.notion.so/mercurial-timer-ec4/5459adf85ac14e839c68592fa1c71764?v=c890e543e76b492583ebddda5fbe2670

**Comment by odelcroi** [comment]
[KeyRequestHandler.js](https://github.com/matrix-org/matrix-react-sdk/pull/4655/files#diff-db89af51273fae40a4aa617b87ca59262a2db22dfcf854f51933bd863b3bc36d) has been removed. One hint would be to revert it into the projet in order to open the missing dialog.

The dialog has been removed also : https://github.com/matrix-org/matrix-react-sdk/pull/4648/files#diff-a248ba2684dc92f20a3e2eba9f63e28a695f739a1736487a398f6380ba558cf6

EDIT : the dialog does not need to be backported, we should use an existing one : IncomingSasDialog
