### ISSUE TITLE
Welcome Page refers to Matrix

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-web-v4#348]
### Steps to reproduce

1. Go to : https://www.tchap.gouv.fr/
2. It will redirect you to : https://www.tchap.gouv.fr/#/welcome

#### What did you expect?
I cannot provide a screenshot for this anymore, but there was a former Welcome Page :
- with blue buttons for sign-in and create account
- no matrix reference
#### What happened instead?
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/3725676/207883851-777750e5-235b-4724-a17b-7f1b869182de.png">

### Will you send logs?

No

**Comment by odelcroi** [comment]
In your opinion, @areox-net is there a problem?

**Comment by areox-net** [comment]
I think we simply use the login page as the first page. 

![Screenshot 2022-12-19 at 11 01 18](https://user-images.githubusercontent.com/1255251/208399548-bf177840-ce01-4736-a4c0-7c174e77367b.png)

**Comment by areox-net** [comment]
Actuallly  https://www.tchap.gouv.fr should redirect to: https://www.tchap.gouv.fr/#/login

**Comment by estellecomment** [comment]
Not any more ! 

<img width="1148" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/9e332671-850e-4850-95d8-fc4cab838cd0">

@areox-net We can also easily skip the welcome page so that people are redirected to the login page (i.e. the login page is the welcome page in practice). If we want to do that, please open a separate ticket, it's not hard to do.
