### ISSUE TITLE
Add unit tests for Room Creation

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#55]
Reuse the test setup that element has, and write a new unit test for TchapCreateRoomDialog.

Sprint goal : https://github.com/tchapgouv/tchap-web-v4/issues/46

**Comment by odelcroi** [comment]
I see multiple tests requirements for this use case : 
- [x] non react component : I've created a separate file for the room creation function, it allows to unit-test easily (no react context needed, pure ts).

- [x] react component events and renders : test component state update based on user input  
- [ ] test view rendering (html..) with snapshots (todo)
- [ ] end to end tests including in matrix-react-sdk 

#52

**Comment by odelcroi** [comment]
In order to run the UT properly we need to "yarn link" the matrix-react-sdk-v4, I managed to do it locally like this
⚠️ Beware to unlink previous version of  matrix-react-sdk before ⚠️ 

- checkout project matrix-react-sdk-v4, tag element-v3.42.0
- yarn link

I set in package.json :  
    "matrix-react-sdk": "github:tchapgouv/matrix-react-sdk-v4#ac3a907",
- yarn link matrix-react-sdk
- yarn test

Before to make any more commit or branch I'd like to discuss with you if this approach seems the right path

**Comment by odelcroi** [comment]
Though, I am not able to run the tests within the folder /node_modules/matrix-react-sdk/test/..

It does not seem trivial : https://github.com/facebook/jest/pull/11084 -> it should be allowed in jest 28 (now using jest 26)

**Comment by estellecomment** [comment]
Adding "blocked" : we should not invest in testing this until we have decided it's our final solution. (we could do design work to see if it would be possible to reuse element's creation dialogs.)

**Comment by jdauphant** [comment]
Lié à https://github.com/tchapgouv/tchap-design/issues/90

**Comment by estellecomment** [comment]
@jdauphant du coup on peut enlever le "blocked" ?

**Comment by jdauphant** [comment]
Oui

**Comment by estellecomment** [comment]
@odelcroi : Discussing this with @mcalinghee : we already have unit tests which verify that the rooms are valid tchap-types.
Next, we need to avoid regressions when we catch up with element.
So what we need is end-to-end tests on this.
Closing this ticket in favor of https://github.com/tchapgouv/tchap-web-v4/issues/117

**Comment by odelcroi** [comment]
I'm submitting a more integrated approach to test React components. This allow to test the logic inside the component as well as the externalized logic. 
I agree that end to end testing is a must go, though it is costly in terms of development and resources to run. For the present case, component testing is enough imho

**Comment by odelcroi** [comment]
Key learnings :  
- The actual configuration does not work with jest 27 or jest 28. It is stuck to jest 26 with an error of typescript transcompilation I guess (babel..).

- The configuration of enzyme is not taken from matrix-react-sdk for an unknown reason. It has been duplicated to a proper setupTests.js file. Though the rest of the configuration from matrix-react-sdk seems to be taken into account.
```
import Adapter from "@wojtekmaj/enzyme-adapter-react-17";
import { configure } from "enzyme";
configure({ adapter: new Adapter() });
```
- only the unit tests are executed to alleviate pressure on computer ressources
```
"testMatch": [
      "<rootDir>/test/unit-tests/**/*-test.[tj]s?(x)"
    ]
```

- the transformIgnorePatterns has been updated in order to work properly  : 
```
"transformIgnorePatterns": [
      "\/node_modules\/(?!matrix-js-sdk|matrix-react-sdk).+$"
    ]
```
