### ISSUE TITLE
Transformation en module de la traduction de l'app

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-web-v4#703]
# Actuellement
Toutes les strings à remplacer sont dans /i18n/tchap_translations.json configurer dans "custom_translations_url".

# Nouvelle méthode
Utilisation d'un module pour charger la traduction :
https://github.com/matrix-org/matrix-react-sdk-module-api#custom-translations--string-overrides
La traduction pourrait même être dynamique (par exemple, automatiquement remplacer "Element" par "Tchap").
Autre utilité, on peut faire des traductions par module, ça rends le code modulaire.

**Comment by estellecomment** [comment]
Necessary for 1.11.44, custom translations are starting to break.

**Comment by jdauphant** [comment]
@estellecomment je pense qu'il faut intégrer les traductions avec nos modules ensuite (avoir un module qui apporte notre comportement + les traductions associés).
Et ne pas avoir un module unique pour toutes les traductions.

**Comment by estellecomment** [comment]
This breaks scalingo builds, because of the `yarn add` that is called by the module installer, during the build phase (not the install phase) . 

After talking to scalingo support, they don't really know why this happens, they suggest we use a custom buildpack in order to be able to see what's inside the container, and debug the problem. They don't know if it will be fixable.

Options : 
 - [ ] debug using custom buildpack
 - [x] remove the `yarn add` by modifying the installer code. If we add our modules as dependencies by hand, then they are still loaded ok. Done here : https://github.com/tchapgouv/tchap-web-v4/pull/776
 - [ ] stop using scalingo. We use scalingo for review apps and internal builds, so I think it's worth having, we would need to find another provider.
 
 Option 2 is definitely the quickest to do. We'd need good arguments for the other two solutions. Thoughts ?

**Comment by estellecomment** [comment]
Done the quick way. We can revisit later if it's too much work to maintain.

**Comment by estellecomment** [comment]
Reopening because there's some weird build problems, i'm not very confident that release builds will really work, and the local builds are messed up.

**Comment by estellecomment** [comment]
Should be good now !
