### ISSUE TITLE
Ability for an external user to change her/his username

### ISSUE THREAD

**Issue by bolinocroustibat** [tchapgouv/tchap-web-v4#880]
### Your use case

It seems that currently external users can't change their username which defaults to their email.
It's inconvenient when doing project management with several external users, since it can be identify to find a user and/or to tag it among several external users.

Would it be possible for external users to change their name, or if not possible for the room admin to do it?

<img width="380" alt="Screenshot 2024-01-23 at 17 07 08" src="https://github.com/tchapgouv/tchap-web-v4/assets/4353767/cca848bd-3fa2-4f91-8ba8-973cc3983722">

**Comment by estellecomment** [comment]
This is a request we also have for internal users. It's a tricky one because we need to make sure that malicious users cannot impersonate someone else by using someone else's name. It's a security problem, especially since Tchap is a professional tool.
But it's also perfectly normal to be able to change when your name is wrong, of course. It's something we want to do !

Thanks for your input ! It helps us prioritize issues.

**Comment by estellecomment** [comment]
Closed in favor of https://github.com/tchapgouv/tchap-product/issues/264
