### ISSUE TITLE
Some rooms are not in the 3 types (public, private, private with externs)

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-web-v4#908]
Several of tchap teams' rooms don't have an icon of one of the 3 types of rooms (public, private, private with externs)

<img width="49" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/911434/bc40b73c-3a52-45a3-adf4-da70cb09af10">

Is it because they are in the Tchap space ? Space-related bug ? Or because they were created by another client ?

**Comment by estellecomment** [comment]
fixed

**Comment by estellecomment** [comment]
ah non pardon

**Comment by MarcWadai** [comment]
After investigation, this issue is caused by a room upgrade (from version 1 to 9), during which the room will not have the correct event set "im.vector.room.access_rules". Since the icon depends on this value to check the type of icon to display, it won't display anything for those rooms.

@odelcroi we talked about it with @estellecomment and there are multiple solutions :
1- remove completely the button to upgrade a room. 
2- Fix on the backend, to add the correct event to the room during the upgrade
3- Do nothing :rofl: 

We tended toward the 1 options which is the easiest.

**Comment by odelcroi** [comment]
> 1- remove completely the button to upgrade a room.

What are the impacts in terms of user UX? 
Upgrading a room is necessary to include them into a space. Withtout this button, people will not be able to add an existing room into a space. 
I would include this issue to the meta "space" issue, and prioritize it regarding this scope. 

Until then, we can P2 this issue
